/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JPTuvBNX8Oh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"
import { TooltipProvider, Tooltip } from "@/components/ui/tooltip"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"

export function ComponentLibrary() {
  return (
    <div className="bg-background text-foreground font-sans">
      <header className="bg-card py-4 shadow-sm">
        <div className="container mx-auto px-4 flex items-center justify-between">
          <h1 className="text-2xl font-bold">UI Component Library</h1>
          <nav>
            <ul className="flex items-center space-x-4">
              <li>
                <Link href="#" className="text-primary hover:text-primary-foreground" prefetch={false}>
                  Components
                </Link>
              </li>
              <li>
                <Link href="#" className="text-primary hover:text-primary-foreground" prefetch={false}>
                  Theming
                </Link>
              </li>
              <li>
                <Link href="#" className="text-primary hover:text-primary-foreground" prefetch={false}>
                  Documentation
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8">
        <section className="mb-12">
          <h2 className="text-3xl font-bold mb-4">Buttons</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <Button>Primary</Button>
            <Button variant="secondary">Secondary</Button>
            <Button variant="outline">Outline</Button>
            <Button variant="ghost">Ghost</Button>
            <Button variant="link">Link</Button>
            <Button variant="danger">Danger</Button>
            <Button variant="success">Success</Button>
            <Button variant="warning">Warning</Button>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-3xl font-bold mb-4">Cards</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Card Title</CardTitle>
                <CardDescription>This is a card description.</CardDescription>
              </CardHeader>
              <CardContent>
                <p>Card content goes here.</p>
              </CardContent>
              <CardFooter>
                <Button>Action</Button>
              </CardFooter>
            </Card>
            <Card variant="elevated">
              <CardHeader>
                <CardTitle>Elevated Card</CardTitle>
                <CardDescription>This is an elevated card.</CardDescription>
              </CardHeader>
              <CardContent>
                <p>Card content goes here.</p>
              </CardContent>
              <CardFooter>
                <Button>Action</Button>
              </CardFooter>
            </Card>
            <Card variant="bordered">
              <CardHeader>
                <CardTitle>Bordered Card</CardTitle>
                <CardDescription>This is a bordered card.</CardDescription>
              </CardHeader>
              <CardContent>
                <p>Card content goes here.</p>
              </CardContent>
              <CardFooter>
                <Button>Action</Button>
              </CardFooter>
            </Card>
            <Card variant="subtle">
              <CardHeader>
                <CardTitle>Subtle Card</CardTitle>
                <CardDescription>This is a subtle card.</CardDescription>
              </CardHeader>
              <CardContent>
                <p>Card content goes here.</p>
              </CardContent>
              <CardFooter>
                <Button>Action</Button>
              </CardFooter>
            </Card>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-3xl font-bold mb-4">Accordion</h2>
          <Accordion>
            <AccordionItem>
              <AccordionTrigger>Accordion Item 1</AccordionTrigger>
              <AccordionContent>
                <p>This is the content of Accordion Item 1.</p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem>
              <AccordionTrigger>Accordion Item 2</AccordionTrigger>
              <AccordionContent>
                <p>This is the content of Accordion Item 2.</p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem>
              <AccordionTrigger>Accordion Item 3</AccordionTrigger>
              <AccordionContent>
                <p>This is the content of Accordion Item 3.</p>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </section>
        <section className="mb-12">
          <h2 className="text-3xl font-bold mb-4">Tooltips</h2>
          <div className="flex justify-center space-x-4">
            <TooltipProvider>
              <Tooltip content="This is a tooltip">
                <Button>Hover me</Button>
              </Tooltip>
              <Tooltip content="This is another tooltip" placement="right">
                <Button>Hover me</Button>
              </Tooltip>
              <Tooltip content="This is a bottom tooltip" placement="bottom">
                <Button>Hover me</Button>
              </Tooltip>
              <Tooltip content="This is a left tooltip" placement="left">
                <Button>Hover me</Button>
              </Tooltip>
            </TooltipProvider>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-3xl font-bold mb-4">Input Fields</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label htmlFor="input1">Input Field</Label>
              <Input id="input1" placeholder="Enter text" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="input2">Textarea</Label>
              <Textarea id="input2" placeholder="Enter text" rows={3} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="input3">Select</Label>
              <Select id="input3">
                <SelectContent>
                  <SelectItem value="option1">Option 1</SelectItem>
                  <SelectItem value="option2">Option 2</SelectItem>
                  <SelectItem value="option3">Option 3</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="input4">Checkbox</Label>
              <Checkbox id="input4">Checkbox Label</Checkbox>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-card py-4 shadow-sm">
        <div className="container mx-auto px-4 flex items-center justify-between">
          <p className="text-muted-foreground">© 2023 UI Component Library</p>
          <div className="flex items-center space-x-4">
            <Link href="#" className="text-primary hover:text-primary-foreground" prefetch={false}>
              GitHub
            </Link>
            <Link href="#" className="text-primary hover:text-primary-foreground" prefetch={false}>
              Documentation
            </Link>
            <Button>Get Started</Button>
          </div>
        </div>
      </footer>
    </div>
  )
}
